"""Add author_id to workshops

Revision ID: e382bbfb1561
Revises: 
Create Date: 2026-08-30 06:33:23.064576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e382bbfb1561'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workshops_author_id'), 'workshops', ['author_id'], unique=False)
    op.create_foreign_key(None, 'workshops', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workshops', type_='foreignkey')
    op.drop_index(op.f('ix_workshops_author_id'), table_name='workshops')
    op.drop_column('workshops', 'author_id')
    # ### end Alembic commands ###
